// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjR5rI8jeV1IxVE6-CyVgqjwOC95_MRc',
    appId: '1:1070571847901:web:c51faf4dc40bd194199b34',
    messagingSenderId: '1070571847901',
    projectId: 'testauthenticaction',
    authDomain: 'testauthenticaction.firebaseapp.com',
    storageBucket: 'testauthenticaction.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZw7WtwCzLObNfglBGYhcu7m3QCkvBFiA',
    appId: '1:1070571847901:android:0e667241779370e1199b34',
    messagingSenderId: '1070571847901',
    projectId: 'testauthenticaction',
    storageBucket: 'testauthenticaction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HgACaxkTCyR3XqQv-bM5hVoDxq8hQbw',
    appId: '1:1070571847901:ios:e0b0037103398466199b34',
    messagingSenderId: '1070571847901',
    projectId: 'testauthenticaction',
    storageBucket: 'testauthenticaction.firebasestorage.app',
    iosBundleId: 'com.example.loginAndRegisterPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HgACaxkTCyR3XqQv-bM5hVoDxq8hQbw',
    appId: '1:1070571847901:ios:e0b0037103398466199b34',
    messagingSenderId: '1070571847901',
    projectId: 'testauthenticaction',
    storageBucket: 'testauthenticaction.firebasestorage.app',
    iosBundleId: 'com.example.loginAndRegisterPages',
  );
}
